## docker-compose.yml — определяет сервисы для разработки и тестирования.
#
#services:
#  db:
#    image: postgres:15
#    container_name: bankcards_db
#    restart: always
#    environment:
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: admin
#      POSTGRES_DB: bankdb
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U admin" ]
#      interval: 5s
#      retries: 5
#      start_period: 5s
#
#  app:
#    build: .
#    depends_on:
#      db:
#        condition: service_healthy
#    environment:
#      environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bankdb
#      SPRING_DATASOURCE_USERNAME: admin
#      SPRING_DATASOURCE_PASSWORD: admin
#      SPRING_PROFILES_ACTIVE: docker
#    ports:
#      - "8080:8080"
#
#volumes:
#  postgres_data:
