# application.yml — главный конфигурационный файл Spring Boot.

spring:
  datasource:
    url: jdbc:postgresql://db:5432/bankdb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/migration/changelog-master.yaml
